# What is Behind Green Industry Motive to Maintain Rural Areas?

### Ali Akbar Anggara 

#### 1. INTRODUCTION

<div style="text-align: JUSTIFY"> The environmental damage is the main factors that causes disasters. In 2004, the United Nations High- Level Threat Challenges and Change Panel explain that environmental degradation as one of ten threats to the world. The waste is one of reason the environmental damage. Since 1950, The amount of waste has always increased. There are significant increase from 1950 until 2015. In 1950 the waste was at 2 million tons per year, and in 2015 the world produced 381 million tons of waste per year. The industrial is main contributor on waste production in kind of plastics as much as 146 million tons (Geyer et al., 2017).
    
<div style="text-align: JUSTIFY"> Then, industrial activities that are mostly in urban areas are contributors on environmental problems. The one of problem that caused by industry is land transition. The activities often exploit resources from rural to an urban area.

<div style="text-align: JUSTIFY"> Today, the company  must be aware that the supply is limit. The everything of raw material sourced by environment has limited supply so that need action to keep the sustainability. Three bottom line is explain that profit, people and planet has become important element for sustainability. So that industry is required to be actively involved in maintaining the rural area alike implementing a green industry. 

<div style="text-align: JUSTIFY"> Green industry practices are achieved through the application of green accounting in accounting practices (Clarkson et al., 2011). Actually, green accounting practice alike disclose environmental information is still voluntary in Indonesia. Even environmental disclosure is an important part of financial statement (Gray, 1994). Environmental disclosure is can be push the company to improve environmental performance because the everything of environmental information which did by company will be publish to the public. Indonesia has constitution Number 40 of 2007 about company, social and environmental responsibility is an obligation that must be carried out by each company. The regulation made by government to push the company in order to interest with environment.

<div style="text-align: JUSTIFY"> The public will be judge based on environmental disclosure (Clarkson et al., 2011). Then, environmental disclosure is one kind of method of the company's responsibilities to the public. It is relevant with theory of legitimacy is explain that stakeholder or community will be involve on legitimacy. Of course, the valuation will be influence to company economic performance (Zhongfu et al., 2011). This term will create the paradigm that the company with excellent environmental performance will disclose excellent environmental information (Ingram and Frazier, 1980; Freedman and Wasley, 1990). However, the application of green industry is like two sides of a coin on the one hand, it will bring benefits to the industry, but on the other side it will cause potential increases in costs and decrease the profit (Zulhaimi, 2015). 
This paper will be answer the benefit for the company if do green industry practice and disclose the environmental information. Based on analysis, this research will explain whether the economic performance is main company motive to did green industry practice. </div>


#### 2. LITERATURE REVIEW

<div style="text-align: JUSTIFY"> This study uses theory of legitimacy and stakeholder as a framework to describe the industry role. Gray et al. (1995) explained that the company sustainability depends on stakeholder. Environmental disclosure is the result of consideration from the company and stakeholders. The companies have responsibilities to each group or individuals who can or have been affected by the company obligation. Stakeholders can control themselves to create decision to take a part on environmental or not (Mitchell et al., 1997).
Legitimacy theory is a company management system that is oriented towards alignments with society, government, individuals and community groups. For this reason, as a system that prioritizes public support, the company's operations must be following the expectations of the community. Legitimacy is considered necessary for companies because the legality of society to the company is a strategic factor for the development of the company in the future. Barkemeyer (2007) revealed that the explanation of the strength of the organization's legitimacy theory in the context of corporate social responsibility in developing countries has two things, namely the ability to place profit maximization motives to make a clearer picture of the company's motivation to increase its social responsibility. Then, the legitimacy of the organization which can include cultural factors that form different institutional pressures in different contexts.
This theory states that the company and the surrounding community have close social relations because both are bound in a social contract. Legitimacy theory states that the existence of a company in an area because it is supported politically and guaranteed by government regulations and parliament which is also a representation of society. Thus, there is an indirect social contract between the company and the community, which in this case gives the city the cost and benefits for corporate sustainability (Andreas, 2011).
According to the theoretical framework, this study will be answer the benefit for stakeholder who concern on environmental and what kind legitimacy will achieve by company. So that the study focused on testing environmental performance and environmental cost as a factors that influence environmental disclosure. These variables are representative from green industry practice on accounting term. Then, this study examine the influence and mediate function from environmental disclosure on economic performance. </div>


#### 3. RESEARCH METHOD

<div style="text-align: JUSTIFY"> Based on the kinds of problems discussed in this study, this type of research is classified as a quantitative approach. The quantitative approach is research carried out by collecting data in the form of numbers and then processed and analyzed to obtain a piece of scientific information behind these numbers (Martono, 2011). This study aims to describe, verify, or test a symptom. (Siswono and Yuli, 2010).
The population in this study is the total number of companies listed on the Indonesia Stock Exchange. This research uses a sample of companies listed as LQ45 companies. Tandelilin (2010) explain that index established by IDX especially for 45 companies who have prospects, financial conditions, and high transaction value. It means, investor and trader are aware on company value which represented by economic value.
Sample selection is made by using a purposive sampling method with predetermined criteria. By using this method, in study expect to get information from specific target groups and to obtain a representative sample according to the specified criteria (Sekaran, 2006).  The requirements are as follows:
a.	The company listed on LQ45 index Indonesia Stock Exchange
b.	Publish their financial statement for 2015, 2016, 2017, and 2018.
c.	Stand on LQ45 index at 2015, 2016 and 2017
d.	Publish a sustainability report at 2015, 2016 and 2017
e.	Following the PROPER program at 2015, 2016 and 2017.
f.	Inform environmental cost in financial statement.
    
</div>


###### 3.1 Conceptual and Operational Definition of Variable

<div style="text-align: JUSTIFY"> 3.1.1	Environmental Performance
Good environmental performance is one term of the company's concern for the earth. Environmental performance is the company's performance in creating a pleasant environment (Suratno et al., 2006). PROPER is used as an environmental performance measurement tool in Indonesia and one of the compliance instruments since 1995. The author uses measurements using the rating scale according to the Ministry of Environment, namely: 
5 = Gold; 4 = Green; 3 = Blue; 2 = Red; 1 = Black </div>

<div style="text-align: JUSTIFY"> 3.1.2	Environmental cost 
The definition of the environment and environmental cost management are stated in PSAK No. 33 concerning general mining accounting. Firoz and Ansari (2010) provide examples of estimates related to environmental costs, including provision of clean-up costs, provision for rehabilitation in the mining industry, provision of claims for contingencies, provision of environmental costs such as overcoming air pollution, noise pollution, gas, and hazardous waste and provision of purchasing equipment to control pollution. The equation as follows: 
Environmental cost = Total environmental cost on rural area (cost). </div>

<div style="text-align: JUSTIFY"> 3.1.3	Environmental Disclosure
Reporting or disclosure of socio-environmental accounting information related to aspects of the interaction between company organizations and the social environment and physical environment (Saudagaran, 2011). GRI is reporting, disclosure of standards that are indicators of social responsibility carried out by the company to create/provide the benefits of reporting to corporate stakeholders. This guideline is designed to be used by organizations in size, sector, or location.
Index GRI G4=  (Total GRI EN item in the company)/( Total environmental item GRI EN) </div>

<div style="text-align: JUSTIFY"> 3.1.4	Economics Performance
Economic performance is the relative performance of a company in the same industry, which is characterized by the annual return of the industry concerned (Suratno et al, 2006). In this study, the authors limit the measurement of the company's economic performance using Tobin’s q. The indicators are using for measuring corporate performance variables from an investment perspective that has been tested in various top management situations (Wolfe and Sauaia, 2003).
Tobin's Q =((Total share x Price)+(Total Liabilities+Inventory-Current Assets))/(Total Assets)
The data is analysed by Multiple Regression technique for analysis factor that influence dependent variable and path Analysis to determine mediate function of environmental disclosure.

</div>

#### 4.	RESULT AND DISCUSSION

<div style="text-align: JUSTIFY"> Result of Descriptive Test Based on Variables is described output from companies sampled based on Environmental Performance (EP), Environmental Cost (EC), Environmental Disclosure (ED) and Economic Performance (EcP). </div>

In [23]:
import pandas as pd
import numpy as np

In [33]:
# importing pandas as pd 
import pandas as pd 
  
# Creating the DataFrame 
df = pd.DataFrame({'EP':[3.4737, 3.00, 0.60345, 3.00, 5.00], 
                   'EC':[86883564908, 3977754008, 90805557774, 3977754008, 363502070000], 
                   'ED':[0.3632, 0.20, 0.23644, 0.10, 0.90],
                   'EcC':[1.2816, 0.90, 0.55549, 0.30, 2.70]}) 
  
# Create the index 
index_ = ['Mean', 'Mode','Std. Deviasi', 'Min', 'Max'] 
  
# Set the index 
df.index = index_ 
  
# Print the DataFrame 
print(df)

                   EP            EC       ED      EcC
Mean          3.47370   86883564908  0.36320  1.28160
Mode          3.00000    3977754008  0.20000  0.90000
Std. Deviasi  0.60345   90805557774  0.23644  0.55549
Min           3.00000    3977754008  0.10000  0.30000
Max           5.00000  363502070000  0.90000  2.70000


<div style="text-align: JUSTIFY"> From Table 1. it can be concluded that the companies that are sampled on average spend an environmental cost of 86.88 billion per year and at least companies spend an environmental cost of 3.97 billion per year. Furthermore, from the data, it can be seen that the environmental performance is good, which is at 3.00, that indicates the company has a blue PROPER rating. Color is explained that companies made environmental management efforts that are required following the provisions and legislation. (kemenlh, 2013). 
Environmental Disclosure shows that average of company who publish sustainability is only follow 12 indexes of GRI (0.3632 x 34 item). Even there is company that only follow 3 indexes of GRI (0.10 x 34 item). GRI has made a standard for sustainability report to report information related to three bottom line, namely profit, people, and the planet. The measure has been used internationally. However, there are still many companies that do not provide complete information. It is because the company does not carry out activities as found in GRI Environmental. </div>


<div style="text-align: JUSTIFY"> 4.2.1	The Influence of Environmental Performance on Environmental Disclosure 
Based on the results of the regression test and path analysis explain that environmental performance is influence on environmental disclosure variables (looks table 4. Summary of Hypothesis test). Preston (1981), Al- Tuwaijri (2004), Clarkson et al. (2011) states that there is a positive relationship between environmental performance and environmental disclosure that companies with high environmental performance have incentives to communicate company information by making environmental disclosure reliable. It means, environmental disclosure will be good or bad depend on environmental performance. 
One of the grand theories in research is the theory of legitimacy. The theory explains the importance of the legitimacy of the public. Environmental performance from a company can answers this theory. Environmental performance has a positive effect (Unstandardized coefficient B = 0.185) on environmental disclosure. This value means that every increase of one PROPER level will increase the influence up to 18.5%. Environmental disclosure becomes a good medium to get attention from stakeholder. The company can build the brand image through environmental disclosure so that the company can get the public sympathy. It shows that excellent environmental performance can provide value to the company. </div>

<div style="text-align: JUSTIFY"> 4.2.2	The Influence of Environmental Cost to Environmental Disclosure 
Environmental costs have an influence although the direction of the negative coefficient results in unstandardized coefficients B = -1.011. When the company reporting environmental cost so much, it will decrease environmental disclosure quality. The company should have report environmental cost but should be consider carefully. It means the company currently considers environmental cost is only an additional expenditure for the company which will eventually become a profit-reducing account for the company application of green accounting to the company is like two sides of a coin, on the one hand it will bring benefits to the industry but on the other hand it will cause potential increases in costs through environmental costs (Zulhaimi, 2015). The situation becomes challenging for management to consider the proportion of environmental costs that will be incurred by the company. The good calculations are needed to control each sides of this coin in order to be optimal. Business is indeed looking for profit, so stakeholders cannot abandon this substance. Actually, it will be good if the company does not report environmental cost because environmental cost has negative influence to environmental disclosure.  </div>

<div style="text-align: JUSTIFY"> 4.2.3	The Influence of Environmental Disclosure and Economics Performance 
Companies publish information about the environment through environmental disclosure aimed at building an image on the company and getting attention from the public. Based on environmental disclosure, stakeholders will understand how the company's role and concern for the environment. These stakeholders will assess and decide whether they will legitimize or even invest. Companies with high environmental disclosures in their financial statements will be more reliable. Reliable financial statements will affect economic performance, where investors will respond positively to higher stock price fluctuations, and vice versa. If the environmental disclosure of a company is low, then investors will react negatively to the variations in stock prices which decrease from year to year. 
Gray (1993) explains that environmental disclosure is an essential part of a company's financial statements. The problem is that environmental disclosure in the annual report in Indonesia is still voluntary even though the Indonesian government has regulated this in regulations, one of which is Republic of Indonesia Law No. 47 of 2012 concerning social and environmental responsibility. Also though environmental disclosure has a positive impact on economic performance (Zhongfu et al., 2011). Stakeholder theory states that the amount of environmental information disclosed by the company will affect stakeholders so that it affects stock prices and affects the company's annual return. Almilia and Wijayanto (2007) found a relationship between environmental disclosure and economic performance.  </div>

<div style="text-align: JUSTIFY"> 4.2.4 Environmental Disclosure is Intervening Variable Between Environmental Performance and Environmental Cost on Economic Performance 
That are influence as directly to economic performance. Both variables are need environmental disclosure as media to show up their value. The variables will be meaningful If the company report environmental performance and environmental cost in special space, that is environmental disclosure. The special space can be highlight for investor and trader who are interest with environmental issues. Based on this study explain that investors and traders are consider environmental performance and environmental costs in investing their money in the LQ45 listed companies. The investors are be aware that taking environmental, social, and corporate governance, or ESG, issues onboard is in the long-term interest of the investments. Not doing so could pose a financial risk to their investments.  </div>

<div style="text-align: JUSTIFY"> Today, market regulators are press the company to disclose information on environmental issues, and given the focus of markets on short-term profit, companies are not always forthcoming with full disclosures on environmental risks even though in Indonesia still as voluntary information. Ceres Network from Socially Responsibility Investment (SRI) explain that today the industry brings an effect to the earth because their activity. It is difficult for the future then need energy and climate change policy. Good environmental disclosure will be to provide complete information to investors. However, excellent environmental performance cannot be separated from the costs that must be incurred to achieve it. During hot issues about environmental campaigns, it is appropriate for stakeholders to start caring about environmental issues. It's time for the Three bottom lines to come true, so it's not just a slogan.  </div>

<div style="text-align: JUSTIFY"> From the discussion, it can conclude that stakeholders in Indonesia have been concerned about environmental issues expressed in environmental disclosure, in this case, through the GRI 4.0 standardized sustainability report. Thus, although environmental disclosure is a type of voluntary disclosure, there is no loss for the company to disclose it to the public. The reason also becomes the basis of environmental performance, and environmental costs do not directly affect economic performance.  It is because investors will easily read clearly when the environmental performance and environmental costs are published in environmental disclosure. Besides, from the test results, it can be ascertained that investors are still sensitive to the environmental cost magnitude. It is because the environmental cost will be a burden that also reduces the company's revenue.  </div>
